export const NONE_VALUE = "none";

export const DISTRICTS = [
  "7 Makara",
  "Khan Toul Kork",
  "Daun Penh",
  "Dong Kao",
  "Mean Chey",
  "Russey Keo",
  "Por Sen Chey",
  "Sen Sok",
  "Chamkarmon",
  "សាលាខណ្ឌច្បារអំពៅ",
  "សាលាខណ្ឌជ្រោយចង្វារ",
  "សាលាខណ្ឌព្រែកព្នៅ",
] as const;

export const PROVINCES = [
  "Banteay Meanchey",
  "Battambang",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Speu",
  "Kampong Thom",
  "Kampot",
  "Kandal",
  "Kep",
  "Koh Kong",
  "Kratie",
  "Mondulkiri",
  "Oddar Meanchey",
  "Pailin",
  "Preah Sihanouk",
  "Preah Vihear",
  "Prey Veng",
  "Pursat",
  "Phnom Penh",
  "Ratanakiri",
  "Siem Reap",
  "Stung Treng",
  "Svay Rieng",
  "Takeo",
  "Tboung Khmum",
] as const;
